package cn.lvsen.test.dao;

import cn.lvsen.test.model.TableData;
import cn.lvsen.test.model.TableDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    long countByExample(TableDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int deleteByExample(TableDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int insert(TableData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int insertSelective(TableData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    List<TableData> selectByExample(TableDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    TableData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") TableData record, @Param("example") TableDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int updateByExample(@Param("record") TableData record, @Param("example") TableDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int updateByPrimaryKeySelective(TableData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    int updateByPrimaryKey(TableData record);
}