package cn.lvsen.test.model;

import java.util.Date;

public class TableData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.id
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.date
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.name
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.province
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.city
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.address
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.zip
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    private Integer zip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.id
     *
     * @return the value of t_table.id
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.id
     *
     * @param id the value for t_table.id
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.date
     *
     * @return the value of t_table.date
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.date
     *
     * @param date the value for t_table.date
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.name
     *
     * @return the value of t_table.name
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.name
     *
     * @param name the value for t_table.name
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.province
     *
     * @return the value of t_table.province
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.province
     *
     * @param province the value for t_table.province
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.city
     *
     * @return the value of t_table.city
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.city
     *
     * @param city the value for t_table.city
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.address
     *
     * @return the value of t_table.address
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.address
     *
     * @param address the value for t_table.address
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.zip
     *
     * @return the value of t_table.zip
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public Integer getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.zip
     *
     * @param zip the value for t_table.zip
     *
     * @mbg.generated Thu Apr 06 17:58:48 CST 2017
     */
    public void setZip(Integer zip) {
        this.zip = zip;
    }
}