package top.slipkinem.admin.po;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.post_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.user_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.username
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_rate
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer commentRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_nemo
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer commentNemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_type
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer commentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_delete
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer commentDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.create_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.update_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_content
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_id
     *
     * @return the value of t_comment.comment_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_id
     *
     * @param commentId the value for t_comment.comment_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.post_id
     *
     * @return the value of t_comment.post_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.post_id
     *
     * @param postId the value for t_comment.post_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.user_id
     *
     * @return the value of t_comment.user_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.user_id
     *
     * @param userId the value for t_comment.user_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.username
     *
     * @return the value of t_comment.username
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.username
     *
     * @param username the value for t_comment.username
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_rate
     *
     * @return the value of t_comment.comment_rate
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getCommentRate() {
        return commentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_rate
     *
     * @param commentRate the value for t_comment.comment_rate
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCommentRate(Integer commentRate) {
        this.commentRate = commentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_nemo
     *
     * @return the value of t_comment.comment_nemo
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getCommentNemo() {
        return commentNemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_nemo
     *
     * @param commentNemo the value for t_comment.comment_nemo
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCommentNemo(Integer commentNemo) {
        this.commentNemo = commentNemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_type
     *
     * @return the value of t_comment.comment_type
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_type
     *
     * @param commentType the value for t_comment.comment_type
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_delete
     *
     * @return the value of t_comment.comment_delete
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getCommentDelete() {
        return commentDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_delete
     *
     * @param commentDelete the value for t_comment.comment_delete
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCommentDelete(Integer commentDelete) {
        this.commentDelete = commentDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.create_time
     *
     * @return the value of t_comment.create_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.create_time
     *
     * @param createTime the value for t_comment.create_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.update_time
     *
     * @return the value of t_comment.update_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.update_time
     *
     * @param updateTime the value for t_comment.update_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_content
     *
     * @return the value of t_comment.comment_content
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_content
     *
     * @param commentContent the value for t_comment.comment_content
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
}