package cn.lvsen.test.po;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_title
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private String postTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.user_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_good
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer postGood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_delete
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Integer postDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.create_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.update_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_content
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    private String postContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_id
     *
     * @return the value of t_post.post_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_id
     *
     * @param postId the value for t_post.post_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_title
     *
     * @return the value of t_post.post_title
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_title
     *
     * @param postTitle the value for t_post.post_title
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.user_id
     *
     * @return the value of t_post.user_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.user_id
     *
     * @param userId the value for t_post.user_id
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_good
     *
     * @return the value of t_post.post_good
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getPostGood() {
        return postGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_good
     *
     * @param postGood the value for t_post.post_good
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setPostGood(Integer postGood) {
        this.postGood = postGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_delete
     *
     * @return the value of t_post.post_delete
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Integer getPostDelete() {
        return postDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_delete
     *
     * @param postDelete the value for t_post.post_delete
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setPostDelete(Integer postDelete) {
        this.postDelete = postDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.create_time
     *
     * @return the value of t_post.create_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.create_time
     *
     * @param createTime the value for t_post.create_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.update_time
     *
     * @return the value of t_post.update_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.update_time
     *
     * @param updateTime the value for t_post.update_time
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_content
     *
     * @return the value of t_post.post_content
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_content
     *
     * @param postContent the value for t_post.post_content
     *
     * @mbg.generated Thu May 25 10:08:55 CST 2017
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }
}